package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.Function;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int insertSelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    Function selectByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Function record);

    List<Function> getAllFunctions();
}