package com.serviceindeed.yike.yikemo.mapper;

import com.serviceindeed.yike.yikemo.domain.KnowledgePointDetail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface KnowledgePointDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long knowledgePointDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    int insert(KnowledgePointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    int insertSelective(KnowledgePointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    KnowledgePointDetail selectByPrimaryKey(Long knowledgePointDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KnowledgePointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_point_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KnowledgePointDetail record);
}